chore: check manual-artifacts for every docker-compose commands

diff --git a/kicker b/kicker
--- a/kicker
+++ b/kicker
@@ -103,6 +103,30 @@ function start() {
     echo -e "\033[0;33mNOTE: The docker-compose version should be newer than 1.28.0\033[0m"
     echo -e "\033[0;33mNOTE: This might take several minutes on the first run\033[0m"
     echo
+
+    if [ "$MANUAL_BUILD_GODWOKEN" = "true" ]; then
+        if [ ! -f "$WORKSPACE/docker/manual-artifacts/godwoken" ]; then
+            error "\"MANUAL_BUILD_GODWOKEN = true\" but \"docker/manual-artifacts/godwoken\" not found"
+            exit 1
+        fi
+        if [ ! -f "$WORKSPACE/docker/manual-artifacts/gw-tools" ]; then
+            error "\"MANUAL_BUILD_GODWOKEN = true\" but \"docker/manual-artifacts/gw-tools\" not found"
+            exit 1
+        fi
+    fi
+    if [ "$MANUAL_BUILD_WEB3" = "true" ]; then
+        if [ ! -f "$WORKSPACE/docker/manual-artifacts/godwoken-web3" ]; then
+            error "\"MANUAL_BUILD_WEB3 = true\" but \"docker/manual-artifacts/godwoken-web3\" not found"
+            exit 1
+        fi
+    fi
+    if [ "$MANUAL_BUILD_WEB3_INDEXER" = "true" ]; then
+        if [ ! -f "$WORKSPACE/docker/manual-artifacts/gw-web3-indexer" ]; then
+            error "\"MANUAL_BUILD_WEB3_INDEXER = true\" but \"docker/manual-artifacts/gw-web3-indexer\" not found"
+            exit 1
+        fi
+    fi
+
     compose up -d --build
     if [ "$?" = "0" ]; then
         info "Services started successfully"
